### ISSUE TITLE
OLCheckPrimaryGamut output inGamut

### ISSUE THREAD

**Issue by JorisVincent** [BrainardLab/OneLightToolbox#39] opened 2018-08-06 21:00 UTC
The function `OLCheckPrimaryGamut` returns a boolean `inGamut`. It is unclear whether this refers to the _original_ input primaries being in gamut, or to the (possibly truncated) _output_ primaries being in gamut. 
It is currently doing the former: even if primaries are truncated to be within gamut, it returns false if they were not already. However, the documentation says:
```
%    inGamut                  - Boolean scalar. True if returned primaries
%                               are in gamut, false if not.  You can only
%                               get false if checkPrimaryOutOfRange is
%                               false.
```
This is NOT how it currently is acting. Is this a bug in code, or a bug in documentation?

**Comment by JorisVincent** [comment] 2018-08-06 21:00
This is not *just* a pedantic question; we rely on this output in several functions, e.g.
`OLPrimaryInvSolveChrom`:
```
    %% Are initial primaries in gamut 
    [initialPrimaries,inGamut] = OLCheckPrimaryGamut(initialPrimaries, ...
        'primaryHeadroom',maxLumPrimaryHeadroom, ...
        'primaryTolerance',p.Results.primaryTolerance, ...
        'checkPrimaryOutOfRange',false);
    if (inGamut)
        % If we're good, break out of loop
        break;
    end
```

**Comment by DavidBrainard** [comment] 2018-08-08 13:54
I looked at this.  I believe the routine to be written as intended and its documentation to be correct.

The purpose of this routine is to check the primaries, but to accept a very small violation of gamut as in gamut.  In cases where the primaries are just a hair out of gamut, it puts them in gamut.  It does not, however, touch input primaries that are out of gamut by more than the primaryTolerance (default 1e-6).

This routine is needed to deal with the fact that routines like fmincon allow a small violation of their constraints, so that primaries that are basically fine can be technically out of gamut.

The return status really is about what is returned, which can differ (by primaryTolerance) from what is passed.

Note that you can obtain a strict check by setting primaryTolerance to 0.  And that primaryTolerance is different from primaryHeadroom.

I expanded the header comments to provide a fuller description along the lines of this comment.

Closing.

**Comment by DavidBrainard** [comment] 2018-08-08 14:30
Rejected PR in favor of keeping old behavior and improving comments, now done.
There is some chance that some piece of code counts on the current behavior.

**Closed** 2018-08-08 14:31 UTC
Labels: bug, question
